const fs = require("fs");
const path = require("path");

// Path to your WASM file
const wasmPath = path.resolve(__dirname, "../src/precompiles/calculator.wasm");

// Output TypeScript file path
const outPath = path.resolve(__dirname, "../src/precompiles/calculator.ts");

// Read WASM file and convert to base64
const b64 = fs.readFileSync(wasmPath).toString("base64");

// Generate TypeScript file with the base64 string
const output = `// Auto-generated by embed_wasm.js - do not edit manually\n\nexport const wasmBase64 = "${b64}";\n`;

// Write the TypeScript file
fs.writeFileSync(outPath, output);
