const fs = require("fs");
const path = require("path");

const wasmPath = path.resolve("./src/evm/precompiles/math.wasm");

const outPath = path.resolve("./src/evm/precompiles/math.ts");

const b64 = fs.readFileSync(wasmPath).toString("base64");

const output = `// Auto-generated by embed_wasm.js - do not edit manually \n\n
export const wasmBase64 = "${b64}";
`;

fs.writeFileSync(outPath, output);
