import type { Status } from "./coord";
import type { Model } from "./build";
import {
    INVARIANT_DESCS,
    SETUP_FACET_DESCS
} from "../../test/harness/scenario";

const dot = (s: Status) =>
    (
        ({ covered: "✅", untagged: "🟡", none: "❌", na: "🚫" }) as Record<
            string,
            string
        >
    )[s] ?? "·";

export function renderMd(model: Model): string {
    const o: string[] = [];
    const s = model.summary;
    o.push("# Dispute coverage grid (generated)");
    o.push("");
    o.push("> Auto-generated by `yarn coverage:grid`. Do not edit by hand.");
    o.push(
        "> Axis (proof types, fields) is parsed live from `contracts/V1/types/*.sol`,"
    );
    o.push(
        "> so a new enum member / struct field appears here as a fresh gap automatically."
    );
    o.push(
        "> Open `COVERAGE_GRID.generated.html` for the interactive sunburst + grid."
    );
    o.push("");
    o.push(
        "Coverage is **distinct scenarios, not test count** — two tests of the same path = one covered cell."
    );
    o.push("");
    o.push(
        `**Scenarios** ${s.scenarios} · **proof types** ${s.proofsCovered}/${s.proofsTotal} · **value-class cells** ${s.cellsCovered}/${s.cellsTotal} reachable (${s.naCells} N/A)`
    );
    o.push("");
    o.push(
        "Legend: ✅ covered (a scenario is described) · 🟡 untagged (test exists, add `@scenario`) · ❌ none (a gap) · 🚫 N/A (not independently reachable — a constraint, not a gap)"
    );
    o.push("");

    o.push("## Proof-type coverage");
    o.push("");
    o.push("| Proof type | Status | mapped @scenario |");
    o.push("|---|---|---|");
    for (const r of model.proofRows)
        o.push(
            `| ${r.member} | ${dot(r.status)} | ${r.mapped.join(", ") || "—"} |`
        );
    o.push("");

    o.push("## Field value-class checklist");
    o.push("");
    o.push(
        "Each value-class is a distinct scenario. `✓` = a scenario covers that path; bare = a gap (the to-do); `🚫` = N/A (not independently reachable)."
    );
    o.push("");
    for (const sr of model.structRows) {
        o.push(`### ${sr.name}  (\`${sr.file}\`)`);
        o.push("");
        o.push("| Field | Covered | Value-classes (✓ = covered · 🚫 = N/A) |");
        o.push("|---|---|---|");
        for (const f of sr.fields) {
            if (f.nested) {
                o.push(
                    `| ${f.name} | — | → nested struct, decomposed in the \`${f.nested}\` section below |`
                );
                continue;
            }
            if (!f.modeled) {
                o.push(
                    `| ⚠ ${f.name} | — | **UNMODELED — add value-classes** |`
                );
                continue;
            }
            const reachable = f.classes.filter((c) => c.reachable);
            const covN = reachable.filter((c) => c.scenarios.length).length;
            const cells = f.classes
                .map((c) =>
                    !c.reachable
                        ? `🚫\`${c.cls}\``
                        : c.scenarios.length
                          ? `✓\`${c.cls}\``
                          : `\`${c.cls}\``
                )
                .join(" · ");
            o.push(`| ${f.name} | ${covN}/${reachable.length} | ${cells} |`);
        }
        o.push("");
    }

    // setup axis: the starting situation each test sets up (distinguishes same-input tests)
    o.push("## Setup — the starting situation each test sets up");
    o.push("");
    o.push(
        "Before a test fires its bad dispute it sets up a situation (`facet:class`): what the proof"
    );
    o.push(
        "contains, whether calldata was posted, whether the catching peer is online. Two tests with"
    );
    o.push(
        "the **same bad input but a different situation** are distinct tests, not duplicates. A class"
    );
    o.push(
        "with no test is a situation nothing exercises yet — not counted as a gap."
    );
    o.push("");
    o.push("| Facet | Class | Status | Scenarios |");
    o.push("|---|---|---|---|");
    for (const r of model.setupRows)
        o.push(
            `| ${r.facet} | \`${r.cls}\` | ${dot(r.status)} | ${r.mapped.join(", ") || "—"} |`
        );
    o.push("");

    o.push("## Glossary");
    o.push("");
    o.push("**`invariant:`** — the property a test proves holds under attack:");
    o.push("");
    for (const [name, desc] of Object.entries(INVARIANT_DESCS))
        o.push(`- \`${name}\` — ${desc}`);
    o.push("");
    o.push(
        "**`setup:`** — the channel/dispute pre-condition the path runs under (`facet:class`); two tests at the same input cell but different setup are distinct reachability paths, not redundant:"
    );
    o.push("");
    for (const [facet, desc] of Object.entries(SETUP_FACET_DESCS))
        o.push(`- \`${facet}:*\` — ${desc}`);
    o.push("");
    const naList = model.structRows.flatMap((sr) =>
        sr.fields.flatMap((f) =>
            f.classes
                .filter((c) => !c.reachable)
                .map((c) => ({
                    k: `${sr.name}.${f.name}:${c.cls}`,
                    r: c.naReason
                }))
        )
    );
    if (naList.length) {
        o.push(
            "**🚫 N/A cells** — modeled but not independently reachable (a constraint, not a gap):"
        );
        o.push("");
        for (const n of naList) o.push(`- \`${n.k}\` — ${n.r}`);
        o.push("");
    }

    o.push("## 🔴 Gap list — uncovered scenarios/paths");
    o.push("");
    if (!model.gaps.length) o.push("_none._");
    for (const g of model.gaps) o.push(`- ${g}`);
    o.push("");

    if (model.errors.length) {
        o.push("## ⚠ DSL errors (a tag the model rejects)");
        o.push("");
        for (const e of model.errors) o.push(`- ${e}`);
        o.push("");
    }

    o.push("## 🔎 Inference cross-check");
    o.push("");
    o.push(
        "Coordinates derived from each test's own calls (asserted enum, `byzantine.*` helper,"
    );
    o.push(
        "stored-proof/slash assertion). Where a tag also declares the key, it's checked against the"
    );
    o.push(
        "derived value — a mismatch is real drift. Tests can therefore drop the derivable keys."
    );
    o.push("");
    if (!model.crossChecks.length)
        o.push(
            "_no mismatches — every declared key agrees with what the test does._"
        );
    for (const c of model.crossChecks) o.push(`- ⚠ ${c}`);
    o.push("");
    return o.join("\n") + "\n";
}
